login:
    path:      /login
    defaults:  { _controller: CatMSAuthBundle:Security:login }
        
login_check:
    path:      /login-check
    defaults:  { _controller: CatMSAuthBundle:Security:loginCheck }

logout:
    path:      /logout
    defaults:  { _controller: CatMSAuthBundle:Security:logout }

generate_new_password:
    path:      /generate-new-password
    defaults:  { _controller: CatMSAuthBundle:Security:generateNewPasswordRequest }


generate_new_password_response:
    path:      /generate-new-password/{userHash}
    defaults:  { _controller: CatMSAuthBundle:Security:generateNewPassword }