cat_ms_frontend:
    resource: "@CatMSFrontendBundle/Resources/config/routing.yml"
    prefix:   /

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

cat_ms_admin:
    resource: "@CatMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /
    
cat_ms_admin_front:
    resource: "@CatMSAdminBundle/Resources/config/front/routing.yml"
    prefix:   /admin   
    
cat_ms_admin_content_manager:
    resource: "@CatMSAdminBundle/Resources/config/content-manager/routing.yml"
    prefix:   /admin/content-manager   
    
cat_ms_admin_media_library:
    resource: "@CatMSAdminBundle/Resources/config/media-library/routing.yml"
    prefix:   /admin/media-library
    
cat_ms_admin_image_group:
    resource: "@CatMSAdminBundle/Resources/config/image-group/routing.yml"
    prefix:   /admin/asset-group   
    
cat_ms_admin_content_group:
    resource: "@CatMSAdminBundle/Resources/config/content-group/routing.yml"
    prefix:   /admin/content-group
    
cat_ms_admin_ajax:
    resource: "@CatMSAdminBundle/Resources/config/ajax/routing.yml"
    prefix:   /admin/ajax

cat_ms_admin_seo:
    resource: "@CatMSAdminBundle/Resources/config/seo/routing.yml"
    prefix:   /admin/seo

catms_auth_user:
    resource: "@CatMSAuthBundle/Resources/config/user/routing.yml"
    prefix:   /admin/user
    
catms_auth_security:
    resource: "@CatMSAuthBundle/Resources/config/security/routing.yml"
    prefix:   /auth
